version: '3'

services: 
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: test
        ports:
            - 27017:27017
        volumes: 
            - mongo_data:/data/db

volumes: 
    mongo_data: